<?include "layout/tag_header.php"?>
 <body class="home page page-id-2 page-template page-template-page-epsilon-php full_width ttype-epsilon tmain-default">
 <div id="site" class="fullwidth"> <!-- #site // Wraps #header, #page-main, #footer - closed in footer -->
	<div id="page"> <!-- #page // Wraps #header, #page-main - closed in footer -->
		<div id="page-canvas">
<?include "layout/header.php"?>
<?include "contents/main.php"?>
						
</div> <!-- END #page-canvas from header -->
</div> <!-- END #page from header -->

<?include "layout/footer.php"?>
</div>
<div class="lay"></div>
<?include "layout/loader.php"?>

<script language="javascript">
   function site_url(path){
      return "<?=SITE_URL?>"+path;
   }
</script>

<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-24670397-1']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script><script type='text/javascript' src='http://ginsen.kyleandirving.netdna-cdn.com/wp-content/themes/platformpro/sections/nav/superfish.js?ver=1.0'></script>
<script type='text/javascript' src='http://ginsen.kyleandirving.netdna-cdn.com/wp-content/themes/platformpro/sections/nav/jquery.bgiframe.min.js?ver=1.0'></script>
</body>
</html>
<!-- Dynamic page generated in 0.499 seconds. -->
<!-- Cached page generated by WP-Super-Cache on 2013-04-08 16:35:39 -->

<!-- Compression = gzip -->